require 'rubygems'

require 'require_relative'
require_relative 'ModelTests/test_require'

require 'rspec/core/rake_task'
require 'rcov/rcovtask'
require 'rake/testtask'

task :default => [:models]

Rcov::RcovTask.new :models do |t|
  t.test_files = FileList["ModelTests/*_spec.rb"]
  t.rcov_opts << "--threshold 50"
  t.rcov_opts << "--exclude /gems/"
  t.rcov_opts << "--text-report --exclude \"/controllers/,spec,/helpers/,/*Tests/\""
end

#Rake::TestTask.new :default do |t|
#  t.verbose = true
#  t.test_files = FileList['system_test.rb']
#end

#RSpec::Core::RakeTask.new do |t|
#  t.pattern = Dir['**/*_spec.rb']
#end
